name: comikl
channels:
  - bioconda
dependencies:
  - python=3.5
  - numpy=1.11.2
  - bedtools=2.26.0
  - ucsc-fatotwobit
  - pandas=0.19
  - pytables=3.2.3.1
  - java-jdk
  - samtools=1.3.1
  - scikit-learn=0.18.*
