name: thor
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - scikit-learn
  - pysam
  - htseq
  - mpmath
  - cython
  - pip
  - pip:
    - RGT>=0.9.8
    - PePr>=1.1.18
