name: macs2
channels:
  - bioconda
dependencies:
  - python=2.7
  - numpy=1.11.2
  - macs2=2.1.1


  # install EpiCSeg: https://github.com/lamortenera/epicseg
  # install TEPIC: https://github.com/SchulzLab/TEPIC
